diff --git a/mm/Kconfig b/mm/Kconfig
index fbdc5c70e..d87366730 100644
--- a/mm/Kconfig
+++ b/mm/Kconfig
 
+config BREAKDOWN_MOD
+	tristate "Breakdown Module"
+

diff --git a/mm/Makefile b/mm/Makefile
index fbadb91df..c7c558824 100644
--- a/mm/Makefile
+++ b/mm/Makefile
 
+obj-$(CONFIG_BREAKDOWN_MOD)	+= breakdown.o
